/**
 * Create AI Test Generation Log Table
 * This script creates the table and all required fields
 */

(function() {
    
    gs.info('========================================');
    gs.info('Creating AI Test Generation Log Table');
    gs.info('========================================\n');
    
    // ==========================================
    // STEP 1: CREATE TABLE
    // ==========================================
    
    var tableName = 'u_ai_test_generation_log';
    var tableLabel = 'AI Test Generation Log';
    
    // Check if table already exists
    var tableCheck = new GlideRecord('sys_db_object');
    tableCheck.addQuery('name', tableName);
    tableCheck.query();
    
    if (tableCheck.next()) {
        gs.info('✅ Table already exists: ' + tableName);
        var tableId = tableCheck.getUniqueValue();
    } else {
        // Create the table
        var tableGr = new GlideRecord('sys_db_object');
        tableGr.initialize();
        tableGr.setValue('name', tableName);
        tableGr.setValue('label', tableLabel);
        tableGr.setValue('super_class', '');  // No parent table
        tableGr.setValue('is_extendable', false);
        tableGr.setValue('live_feed', false);
        
        var tableId = tableGr.insert();
        
        if (tableId) {
            gs.info('✅ Created table: ' + tableName);
        } else {
            gs.error('❌ Failed to create table');
            return;
        }
    }
    
    // ==========================================
    // STEP 2: DEFINE FIELDS TO CREATE
    // ==========================================
    
    var fields = [
        // Basic Information
        {
            name: 'u_story',
            label: 'User Story',
            type: 'reference',
            reference: 'rm_story',
            mandatory: true,
            description: 'Reference to the user story'
        },
        {
            name: 'u_generated_at',
            label: 'Generated At',
            type: 'glide_date_time',
            mandatory: true,
            description: 'When the generation occurred'
        },
        {
            name: 'u_generated_by',
            label: 'Generated By',
            type: 'reference',
            reference: 'sys_user',
            mandatory: false,
            description: 'User who triggered the generation'
        },
        
        // Results
        {
            name: 'u_success',
            label: 'Success',
            type: 'boolean',
            mandatory: true,
            description: 'Whether generation was successful'
        },
        {
            name: 'u_test_count',
            label: 'Test Count',
            type: 'integer',
            mandatory: false,
            description: 'Number of tests successfully created'
        },
        {
            name: 'u_failed_count',
            label: 'Failed Count',
            type: 'integer',
            mandatory: false,
            description: 'Number of tests that failed to create'
        },
        {
            name: 'u_error_message',
            label: 'Error Message',
            type: 'string',
            max_length: 4000,
            mandatory: false,
            description: 'Error message if generation failed'
        },
        
        // Performance
        {
            name: 'u_duration_seconds',
            label: 'Duration (seconds)',
            type: 'integer',
            mandatory: false,
            description: 'How long the generation took'
        },
        
        // Token Usage
        {
            name: 'u_input_tokens',
            label: 'Input Tokens',
            type: 'integer',
            mandatory: false,
            description: 'Number of input tokens used'
        },
        {
            name: 'u_output_tokens',
            label: 'Output Tokens',
            type: 'integer',
            mandatory: false,
            description: 'Number of output tokens generated'
        },
        {
            name: 'u_total_tokens',
            label: 'Total Tokens',
            type: 'integer',
            mandatory: false,
            description: 'Total tokens used (input + output)'
        },
        
        // Cost Tracking
        {
            name: 'u_model',
            label: 'AI Model',
            type: 'string',
            max_length: 40,
            mandatory: false,
            description: 'AI model used (e.g., gpt-4)'
        },
        {
            name: 'u_input_cost',
            label: 'Input Cost (USD)',
            type: 'decimal',
            mandatory: false,
            description: 'Cost for input tokens'
        },
        {
            name: 'u_output_cost',
            label: 'Output Cost (USD)',
            type: 'decimal',
            mandatory: false,
            description: 'Cost for output tokens'
        },
        {
            name: 'u_estimated_cost',
            label: 'Estimated Cost (USD)',
            type: 'decimal',
            mandatory: false,
            description: 'Total estimated cost'
        }
    ];
    
    // ==========================================
    // STEP 3: CREATE EACH FIELD
    // ==========================================
    
    gs.info('\nCreating fields...\n');
    
    var createdCount = 0;
    var skippedCount = 0;
    
    for (var i = 0; i < fields.length; i++) {
        var field = fields[i];
        
        // Check if field already exists
        var fieldCheck = new GlideRecord('sys_dictionary');
        fieldCheck.addQuery('name', tableName);
        fieldCheck.addQuery('element', field.name);
        fieldCheck.query();
        
        if (fieldCheck.next()) {
            gs.info('  ⏭️  Field already exists: ' + field.label + ' (' + field.name + ')');
            skippedCount++;
            continue;
        }
        
        // Create the field
        var fieldGr = new GlideRecord('sys_dictionary');
        fieldGr.initialize();
        fieldGr.setValue('name', tableName);
        fieldGr.setValue('element', field.name);
        fieldGr.setValue('column_label', field.label);
        fieldGr.setValue('internal_type', field.type);
        fieldGr.setValue('mandatory', field.mandatory || false);
        fieldGr.setValue('active', true);
        
        // Set type-specific attributes
        if (field.max_length) {
            fieldGr.setValue('max_length', field.max_length);
        }
        
        if (field.reference) {
            fieldGr.setValue('reference', field.reference);
        }
        
        if (field.description) {
            fieldGr.setValue('comments', field.description);
        }
        
        var fieldId = fieldGr.insert();
        
        if (fieldId) {
            gs.info('  ✅ Created field: ' + field.label + ' (' + field.name + ')');
            createdCount++;
        } else {
            gs.error('  ❌ Failed to create field: ' + field.name);
        }
    }
    
    // ==========================================
    // STEP 4: CREATE DEFAULT VIEW (LIST LAYOUT)
    // ==========================================
    
    gs.info('\nConfiguring default list view...');
    
    // Note: List layouts are typically created automatically
    // You can manually configure them via: Tables & Columns → [Your Table] → List Layout
    
    gs.info('✅ Table structure created');
    
    // ==========================================
    // SUMMARY
    // ==========================================
    
    gs.info('\n========================================');
    gs.info('SUMMARY');
    gs.info('========================================');
    gs.info('Table Name:       ' + tableName);
    gs.info('Table Label:      ' + tableLabel);
    gs.info('Fields Created:   ' + createdCount);
    gs.info('Fields Skipped:   ' + skippedCount);
    gs.info('Total Fields:     ' + fields.length);
    gs.info('========================================\n');
    
    gs.info('✅ COMPLETE! Navigate to the table:');
    gs.info('   ' + tableName + '.list');
    gs.info('\nOr go to: All → AI Test Generation Log\n');
    
})();